# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/iot/rentcar/client/mypage.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mypage(object):
    def setupUi(self, mypage):
        mypage.setObjectName("mypage")
        mypage.resize(458, 416)
        self.label = QtWidgets.QLabel(mypage)
        self.label.setGeometry(QtCore.QRect(160, 0, 181, 81))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.name_text = QtWidgets.QTextBrowser(mypage)
        self.name_text.setGeometry(QtCore.QRect(35, 260, 91, 31))
        self.name_text.setObjectName("name_text")
        self.label_3 = QtWidgets.QLabel(mypage)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 151, 141))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/home/iot/rentcar/client/../사진/짱구.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(mypage)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 90, 151, 161))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.id_text = QtWidgets.QTextBrowser(mypage)
        self.id_text.setGeometry(QtCore.QRect(280, 90, 161, 31))
        self.id_text.setObjectName("id_text")
        self.label_2 = QtWidgets.QLabel(mypage)
        self.label_2.setGeometry(QtCore.QRect(200, 100, 67, 17))
        self.label_2.setObjectName("label_2")
        self.pw_text = QtWidgets.QTextBrowser(mypage)
        self.pw_text.setGeometry(QtCore.QRect(280, 140, 161, 31))
        self.pw_text.setObjectName("pw_text")
        self.label_4 = QtWidgets.QLabel(mypage)
        self.label_4.setGeometry(QtCore.QRect(190, 150, 67, 17))
        self.label_4.setObjectName("label_4")
        self.reserv_text = QtWidgets.QTextBrowser(mypage)
        self.reserv_text.setGeometry(QtCore.QRect(280, 190, 161, 61))
        self.reserv_text.setObjectName("reserv_text")
        self.label_5 = QtWidgets.QLabel(mypage)
        self.label_5.setGeometry(QtCore.QRect(200, 210, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(mypage)
        self.label_6.setGeometry(QtCore.QRect(151, 329, 67, 17))
        self.label_6.setObjectName("label_6")
        self.cash_text = QtWidgets.QTextBrowser(mypage)
        self.cash_text.setGeometry(QtCore.QRect(149, 350, 101, 31))
        self.cash_text.setObjectName("cash_text")
        self.label_7 = QtWidgets.QLabel(mypage)
        self.label_7.setGeometry(QtCore.QRect(280, 330, 67, 17))
        self.label_7.setObjectName("label_7")
        self.mile_text = QtWidgets.QTextBrowser(mypage)
        self.mile_text.setGeometry(QtCore.QRect(280, 350, 101, 31))
        self.mile_text.setObjectName("mile_text")
        self.change = QtWidgets.QPushButton(mypage)
        self.change.setGeometry(QtCore.QRect(380, 350, 51, 31))
        self.change.setObjectName("change")
        self.textBrowser_8 = QtWidgets.QTextBrowser(mypage)
        self.textBrowser_8.setGeometry(QtCore.QRect(140, 320, 301, 81))
        self.textBrowser_8.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"border-radius:8px;")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.cancle = QtWidgets.QPushButton(mypage)
        self.cancle.setGeometry(QtCore.QRect(280, 250, 161, 25))
        self.cancle.setObjectName("cancle")
        self.textBrowser_8.raise_()
        self.textBrowser_2.raise_()
        self.label.raise_()
        self.name_text.raise_()
        self.label_3.raise_()
        self.id_text.raise_()
        self.label_2.raise_()
        self.pw_text.raise_()
        self.label_4.raise_()
        self.reserv_text.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.cash_text.raise_()
        self.label_7.raise_()
        self.mile_text.raise_()
        self.change.raise_()
        self.cancle.raise_()

        self.retranslateUi(mypage)
        QtCore.QMetaObject.connectSlotsByName(mypage)

    def retranslateUi(self, mypage):
        _translate = QtCore.QCoreApplication.translate
        mypage.setWindowTitle(_translate("mypage", "Dialog"))
        self.label.setText(_translate("mypage", "마이페이지"))
        self.label_2.setText(_translate("mypage", "아이디"))
        self.label_4.setText(_translate("mypage", "패스워드"))
        self.label_5.setText(_translate("mypage", "예약"))
        self.label_6.setText(_translate("mypage", "캐시"))
        self.label_7.setText(_translate("mypage", "마일리지"))
        self.change.setText(_translate("mypage", "교환"))
        self.cancle.setText(_translate("mypage", "예약취소"))
